import { useEffect,useRef,useState,type FormEvent } from 'react'
import type { Prize } from '../models/prize';import type { Store } from '../models/store';import type { PlayResult } from '../models/play'
import { prizeService } from '../services/prizeService';import { storeService } from '../services/storeService';import { playService,todayKey } from '../services/playService'
interface Props{onBack:()=>void}
const nowTime=()=>{const d=new Date();return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
export function ApproximateEntry({onBack}:Props){const [stores,setStores]=useState<Store[]>([]);const [prizes,setPrizes]=useState<Prize[]>([]);const [storeId,setStoreId]=useState('');const [prizeId,setPrizeId]=useState('');const [date,setDate]=useState(todayKey());const [time,setTime]=useState(nowTime());const [amount,setAmount]=useState('');const [result,setResult]=useState<PlayResult>('獲得');const [message,setMessage]=useState('');const [error,setError]=useState('');const [saving,setSaving]=useState(false)
 const saveLock=useRef(false)
 useEffect(()=>{void Promise.all([storeService.listActive(),prizeService.listActive()]).then(([s,p])=>{setStores(s);setPrizes(p);setStoreId(s[0]?.id??'');setPrizeId(p[0]?.id??'')}).catch(()=>setError('店舗と景品を読み込めませんでした。アプリを再読み込みしてください。'))},[])
 const submit=async(e:FormEvent)=>{e.preventDefault();if(saveLock.current)return;saveLock.current=true;try{setSaving(true);setError('');await playService.createApproximate({storeId,prizeId,playDate:date,playTime:time,amount:Number(amount),result});setMessage('うろ覚え記録を保存しました。');setAmount('')}catch(err){setError(err instanceof Error?err.message:'保存できませんでした。')}finally{saveLock.current=false;setSaving(false)}}
 const safeBack=()=>{if(amount&& !confirm('入力中のうろ覚え記録を破棄して戻りますか？'))return;onBack()}
 return <div className="app-shell"><header className="page-header"><button className="back-button" type="button" onClick={safeBack}>‹</button><div><p className="app-eyebrow">APPROXIMATE ENTRY</p><h1>うろ覚え記入</h1></div></header><main className="store-main"><p className="memory-note">正確でなくても構いません。保存後は「概算・うろ覚え」として区別されます。</p>{stores.length===0||prizes.length===0?<p className="list-empty">先に店舗と景品を1件以上登録してください。</p>:<form className="memory-form" onSubmit={submit}><label>店舗<select value={storeId} onChange={e=>setStoreId(e.target.value)}>{stores.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>景品<select value={prizeId} onChange={e=>setPrizeId(e.target.value)}>{prizes.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="form-row"><label>日付<input type="date" max={todayKey()} value={date} onChange={e=>setDate(e.target.value)}/></label><label>時刻<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label></div><label>概算の使用金額（円）<input type="number" inputMode="numeric" min="1" max="1000000" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="例：1500"/></label><fieldset><legend>結果</legend><div className="memory-results">{(['獲得','撤退','アシスト獲得'] as PlayResult[]).map(item=><button type="button" className={result===item?'selected':''} onClick={()=>setResult(item)} key={item}>{item}</button>)}</div></fieldset><button className="primary-wide-button" disabled={saving} type="submit">{saving?'保存中…':'うろ覚え記録を保存'}</button></form>}{error&&<p className="feedback error-message">{error}</p>}{message&&<p className="feedback success-message">{message}</p>}</main></div>}
