import { useEffect,useState,type FormEvent } from 'react'
import type { Prize } from '../models/prize'
import type { PlayResult } from '../models/play'
import type { VisitPlayDetail,VisitSummary } from '../models/visit'
import { playService,todayKey } from '../services/playService'
import { prizeService } from '../services/prizeService'
import { visitService } from '../services/visitService'
interface Props{visit:VisitSummary;prizeId:string;onBack:()=>void;onAdd:(prize:Prize)=>void}
const yen=(n:number)=>`${n.toLocaleString()}円`;const clock=(iso:string)=>new Intl.DateTimeFormat('ja-JP',{hour:'2-digit',minute:'2-digit'}).format(new Date(iso));const errorText=(error:unknown)=>error instanceof Error?error.message:'処理に失敗しました。'
export function PrizeVisitDetail({visit,prizeId,onBack,onAdd}:Props){
 const [prize,setPrize]=useState<Prize|null>(null);const [plays,setPlays]=useState<VisitPlayDetail[]>([]);const [editingId,setEditingId]=useState<string|null>(null);const [amount,setAmount]=useState('');const [result,setResult]=useState<PlayResult>('獲得');const [memo,setMemo]=useState('');const [isApproximate,setIsApproximate]=useState(false);const [playDate,setPlayDate]=useState('');const [playTime,setPlayTime]=useState('');const [message,setMessage]=useState('');const [error,setError]=useState('');const [saving,setSaving]=useState(false)
 const reload=async()=>{const [prizes,all]=await Promise.all([prizeService.list(),visitService.details(visit.storeId,visit.playDate)]);setPrize(prizes.find(item=>item.id===prizeId)??null);setPlays(all.filter(item=>item.prizeId===prizeId))}
 useEffect(()=>{void Promise.all([prizeService.list(),visitService.details(visit.storeId,visit.playDate)]).then(([prizes,all])=>{setPrize(prizes.find(item=>item.id===prizeId)??null);setPlays(all.filter(item=>item.prizeId===prizeId))})},[visit.storeId,visit.playDate,prizeId])
 const startEdit=(play:VisitPlayDetail)=>{const date=new Date(play.startedAt);setEditingId(play.id);setAmount(String(play.amount));setResult(play.result);setMemo(play.memo);setIsApproximate(play.isApproximate);setPlayDate([date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-'));setPlayTime(`${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`);setMessage('');setError('')}
 const cancelEdit=()=>{setEditingId(null);setError('')}
 const save=async(event:FormEvent)=>{event.preventDefault();try{setSaving(true);setError('');const moved=playDate!==visit.playDate;await playService.update(editingId!,{amount:Number(amount),result,memo,isApproximate,playDate,playTime});setEditingId(null);setMessage(moved?`${playDate.replaceAll('-',' / ')}の来店履歴へ移動しました。`:'プレイ記録を更新しました。');await reload()}catch(e){setError(errorText(e))}finally{setSaving(false)}}
 const remove=async(play:VisitPlayDetail)=>{if(!confirm(`${clock(play.startedAt)}のプレイ記録を削除しますか？`))return;try{setError('');await playService.remove(play.id);if(editingId===play.id)setEditingId(null);setMessage('プレイ記録を削除しました。');await reload()}catch(e){setError(errorText(e))}}
 const spent=plays.reduce((s,p)=>s+p.amount,0);const won=plays.filter(p=>p.result!=='撤退').length;const value=plays.reduce((s,p)=>s+p.estimatedValue,0);const isToday=visit.playDate===todayKey()
 return <div className="app-shell"><header className="page-header"><button className="back-button" type="button" onClick={onBack}>‹</button><div><p className="app-eyebrow">PRIZE DETAIL</p><h1>景品詳細</h1></div></header><main className="store-main">{prize?.imageDataUrl&&<img className="prize-detail-photo" src={prize.imageDataUrl} alt={`${prize.name}の写真`}/>}<section className="prize-detail-hero"><p>{visit.playDate.replaceAll('-',' / ')}・{visit.storeName}</p><h2>{prize?.name??plays[0]?.prizeName??'景品'}</h2><span>{prize?.category??plays[0]?.category}</span></section>{prize&&(prize.priceReferenceName||prize.priceReferenceUrl||prize.priceCheckedAt)&&<section className="price-reference-card"><h3>参考価格の情報</h3><dl>{prize.priceReferenceName&&<div><dt>参考元</dt><dd>{prize.priceReferenceName}</dd></div>}{prize.priceCheckedAt&&<div><dt>確認日</dt><dd>{prize.priceCheckedAt.replaceAll('-',' / ')}</dd></div>}{prize.priceReferenceUrl&&<div><dt>参考URL</dt><dd><a href={prize.priceReferenceUrl} target="_blank" rel="noreferrer">商品ページを開く</a></dd></div>}</dl></section>}<section className="today-summary"><div><span>総使用額</span><strong>{yen(spent)}</strong></div><div><span>獲得数</span><strong>{won}個</strong></div><div><span>損益</span><strong>{value-spent>=0?'+':''}{yen(value-spent)}</strong></div></section>
 {error&&<p className="feedback error-message" role="alert">{error}</p>}{message&&<p className="feedback success-message" role="status">{message}</p>}
 <h3 className="detail-subtitle">この日のプレイ履歴</h3><ol className="play-history editable-play-history">{plays.map((play,index)=><li key={play.id}>{editingId===play.id?<form className="play-edit-form" onSubmit={save}><div className="form-row"><label>日付<input type="date" max={todayKey()} value={playDate} onChange={e=>setPlayDate(e.target.value)}/></label><label>時刻<input type="time" value={playTime} onChange={e=>setPlayTime(e.target.value)}/></label></div><div className="form-row"><label>使用額（円）<input type="number" inputMode="numeric" min="1" max="1000000" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>結果<select value={result} onChange={e=>setResult(e.target.value as PlayResult)}><option>獲得</option><option>撤退</option><option>アシスト獲得</option></select></label></div><label>メモ（任意）<textarea maxLength={200} value={memo} onChange={e=>setMemo(e.target.value)} placeholder="台の特徴や取り方など"/></label><label className="approximate-check"><input type="checkbox" checked={isApproximate} onChange={e=>setIsApproximate(e.target.checked)}/>概算・うろ覚え記録として扱う</label><div className="play-edit-actions"><button type="button" onClick={cancelEdit}>キャンセル</button><button type="submit" disabled={saving}>{saving?'保存中…':'変更を保存'}</button></div></form>:<><div className="play-history-content"><span>{index+1}回目・{clock(play.startedAt)}・{play.result}{play.isApproximate?'・概算':''}</span><strong>{yen(play.amount)}</strong>{play.memo&&<small>{play.memo}</small>}</div><div className="play-record-actions"><button type="button" onClick={()=>startEdit(play)}>編集</button><button className="delete-button" type="button" onClick={()=>void remove(play)}>削除</button></div></>}</li>)}</ol>
 {plays.length===0&&<p className="list-empty">この景品のプレイ記録はありません。</p>}{isToday&&prize?<button className="primary-wide-button" type="button" onClick={()=>onAdd(prize)}>この景品にプレイを追加</button>:<p className="past-notice">過去日の記録に現在日のプレイは追加されません。登録済み内容の修正と削除は可能です。</p>}</main></div>}
